export default [
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "x   xxx   x   x    xxxxxxxxxxxx    xxxx      xxxxxx    xxxx   xxxx",
  "x xxxxx   x   xxx xxxxxxx    xx xx xxx   xx   xxxx  xx  xx   x xxx",
  "x xx  x xxxx xxxx xxxxxxx    xx x  xx    xx   xxx   xx   x   x xxx",
  "x       x    xxxx xxxxxx   xxx      x   xx    xxx  xx  x x xx x xx",
  "x xx xx x   xx  x xx  xx  xxx  xx  xxxx  xxx  xxx xx x x x xx x xx",
  "x  x x      xx  x x tt x  xxx  xx  xx  x  xx xxx  xx x x   xx   xx",
  "x  x x  tt  xx  x x tttx  xxx  xx   s  x  xx x    xx x x x xx x xx",
  "x    xxxx xxxx    t t tx  xxx  x    xxxx  x       xx   x x    x  x",
  "x     xx    xxx xxxxxxxx   x   x    x     xxxxxxxxxx xxx xxxxxx  x",
  "x     x     x              x   x          xxxxxx     x x         x",
  "x     x         xxxxxxxxxxxx   x    xxxxx    xxx  xx   xxxxxxxxxxx",
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
];
